version: 2.1

# Define the executors to be used in the jobs
executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:1.5.0  # Use the official Terraform Docker image
    working_directory: ~/repo  # Set the working directory for the executor

# Define the jobs to be executed
jobs:
  prepare:
    executor: terraform-executor
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Install AWS CLI
          command: |
            apt-get update && apt-get install -y awscli  # Install AWS CLI for AWS interactions
      - run:
          name: Terraform Init
          command: terraform init  # Initialize Terraform configuration

  plan:
    executor: terraform-executor
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Terraform Validate
          command: terraform validate  # Validate the Terraform configuration
      - run:
          name: Terraform Plan
          command: |
            terraform plan -out=tfplan_tgw  # Create a Terraform execution plan
            echo "Saving plan to workspace"  # Inform about saving the plan
            circleci workspace save tfplan_tgw  # Save the plan to CircleCI workspace

    manual_approval:
      type: approval  # Define a manual approval step

  apply:
    executor: terraform-executor
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Apply the Terraform Plan
          command: terraform apply "tfplan_tgw"  # Apply the saved Terraform plan

    approve-destroy:
    type: approval  # Define a manual approval step for destruction

  terraform-destroy:
    executor: terraform-executor
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Initialize Terraform
          command: terraform init  # Initialize Terraform for destruction
      - run:
          name: Terraform Destroy
          command: terraform destroy -auto-approve  # Destroy the infrastructure without confirmation

# Define the workflows to orchestrate the jobs
workflows:
  version: 2
  tgw_deployment:
    jobs:
      - prepare  # Run the prepare job first
      - plan:
          requires:
            - prepare  # Run the plan job after prepare
      - manual_approval:
          requires:
            - plan  # Wait for manual approval after the plan job
      - apply:
          requires:
            - manual_approval  # Apply the plan after approval

  terraform_workflow:
    jobs:
      - terraform-plan:
          requires:
            - prepare  # Ensure the prepare job runs before the plan
      - approve-apply:
          requires:
            - terraform-plan  # Wait for approval after the plan job
      - terraform-apply:
          requires:
            - approve-apply  # Apply the plan after approval
      - approve-destroy:
          requires:
            - terraform-apply  # Wait for approval before destruction
      - terraform-destroy:
          requires:
            - approve-destroy  # Destroy the infrastructure after approval
          filters:
            branches:
              only: main  # Only run this job on the main branch