version: 2.1

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:latest

jobs:
  prepare:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            Install AWS CLI

      - run:
          name: Install Terraform
          command: |
            curl -LO https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
            unzip terraform_1.0.0_linux_amd64.zip
            mv terraform /usr/local/bin/
            terraform --version
      - run:
          name: Terraform Initialization
          command: terraform init

  plan:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Terraform Validation
          command: terraform validate
      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan_tgw
      - persist_to_workspace:
          root: .
          paths:
            - tfplan_tgw

  approval:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Manual Approval
          command: |
            echo "Please review the plan and approve to continue."

  apply:
    executor: terraform-executor
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Terraform Apply
          command: terraform apply /workspace/tfplan_tgw

workflows:
  version: 2
  deploy:
    jobs:
      - prepare
      - plan:
          requires:
            - prepare
      - approval:
          requires:
            - plan
      - apply:
          requires:
            - approval