version: 2.1

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/repo

jobs:
  plan-destroy:
    executor: terraform-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform Destroy Plan
          command: |
            terraform plan -destroy -out tfdestroy
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    executor: terraform-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform Destroy
          command: |
            terraform apply -auto-approve tfdestroy

  plan-apply:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Terraform Init & Plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    executor: terraform-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform Apply
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-destroy
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - hold-destroy
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply