version: 2.1

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/repo

jobs:
  plan-apply:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Terraform Init & Plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply 
      - run:
          name: Review Plan Attributes
          command: |
            sudo apt-get install jq
            cat plan.json | jq '.resource_changes[] | {address: .address, change: .change}'
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    executor: terraform-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform Apply
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    executor: terraform-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform Destroy Plan
          command: |
            terraform plan -destroy -out tfdestroy 
      - run:
          name: Review Destroy Plan Attributes
          command: |
            sudo apt-get install jq
            cat destroy_plan.json | jq '.resource_changes[] | {address: .address, change: .change}' 
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    executor: terraform-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform Destroy
          command: |
            terraform apply -auto-approve tfdestroy

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply
      - plan-destroy:
          requires:
            - apply
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - hold-destroy