version: 2.1

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:latest

jobs:
  prepare:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: sudo apt-get install awscli
      - run:
          name: Terraform Init
          command: terraform init

  plan:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan_tgw
      - persist_to_workspace:
          root: .
          paths:
            - tfplan_tgw

    manual_approval:
     type: approval

  apply:
    executor: terraform-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Terraform Apply
          command: terraform apply tfplan_tgw

workflows:
  version: 2
  tgw_deploy:
    jobs:
      - prepare
      - plan
      - manual_approval
      - apply
