version: 2.1

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/repo

jobs:
  prepare:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            apt-get update && apt-get install -y awscli
      - run:
          name: Terraform Init
          command: terraform init

  plan:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Terraform Validate
          command: terraform validate
      - run:
          name: Terraform Plan
          command: |
            terraform plan -out=tfplan_tgw
            echo "Saving plan to workspace"
            circleci workspace save tfplan_tgw

    manual_approval:
    type: approval

  apply:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Apply the Terraform Plan
          command: terraform apply "tfplan_tgw"

workflows:
  version: 2
  tgw_deployment:
    jobs:
      - prepare
      - plan:
          requires:
            - prepare
      - manual_approval:
          requires:
            - plan
      - apply:
          requires:
            - manual_approval
