version: 2.1

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /home/circleci/repo  # Specify an absolute path

jobs:
  prepare:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Install jq
          command: apk add --no-cache jq  # Use this if your image supports apk (Alpine Linux)
      - run:
          name: Terraform Init
          command: terraform init

  plan:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Terraform Validate
          command: terraform validate
      - run:
          name: Terraform Plan
          command: |
            terraform plan -out=tfplan_tgw
            echo "Saving plan to workspace"
      - persist_to_workspace:
          root: .
          paths:
            - tfplan_tgw

  apply:
    executor: terraform-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Apply the Terraform Plan
          command: terraform apply "tfplan_tgw"

  terraform-destroy:
    executor: terraform-executor  # Correct the executor name here
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: terraform init
      - run:
          name: Terraform Destroy
          command: terraform destroy -auto-approve

workflows:
  version: 2
  tgw_deployment:
    jobs:
      - prepare
      - plan:
          requires:
            - prepare
      - approve-destroy:  # Fix job name to match 'approve-destroy'
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - approve-destroy
      - terraform-destroy:
          requires:
            - approve-destroy
          filters:
            branches:
              only: main
